package org.restcomm.protocols.ss7.tcap.api.tc.dialog.events;

import org.restcomm.protocols.ss7.sccp.parameter.SccpAddress;
import org.restcomm.protocols.ss7.tcap.asn.AbortSource;
import org.restcomm.protocols.ss7.tcap.asn.ApplicationContextName;
import org.restcomm.protocols.ss7.tcap.asn.ResultSourceDiagnostic;
import org.restcomm.protocols.ss7.tcap.asn.UserInformation;

/**
 * <pre>
 * -- NOTE � When the Abort Message is generated by the
 * Transaction sublayer, a p-Abort Cause must be
 * -- present.The u-abortCause may be generated by the
 * component sublayer in which case it is an ABRT
 * -- APDU, or by the TC-User in which case it could be
 * either an ABRT APDU or data in some user-defined
 * -- abstract syntax.
 * </pre>
 *
 * ..................
 *
 * @author amit bhayani
 * @author baranowb
 */
public interface TCUserAbortIndication extends DialogIndication {

    /**
     * Returns true if AARE Apdu is included
     *
     * @return
     */
    Boolean IsAareApdu();

    /**
     * Returns true if ABRT Apdu is included
     *
     * @return
     */
    Boolean IsAbrtApdu();

    UserInformation getUserInformation();

    AbortSource getAbortSource();

    ApplicationContextName getApplicationContextName();

    ResultSourceDiagnostic getResultSourceDiagnostic();

    SccpAddress getOriginatingAddress();

}
