package org.restcomm.protocols.ss7.tcap.api.tc.dialog.events;

import org.restcomm.protocols.ss7.sccp.parameter.SccpAddress;
import org.restcomm.protocols.ss7.tcap.asn.ApplicationContextName;
import org.restcomm.protocols.ss7.tcap.asn.DialogServiceUserType;
import org.restcomm.protocols.ss7.tcap.asn.UserInformation;

/**
 * <pre>
 * -- NOTE � When the Abort Message is generated by the Transaction sublayer, a p-Abort Cause must be
 * -- present.The u-abortCause may be generated by the component sublayer in which case it is an ABRT
 * -- APDU, or by the TC-User in which case it could be either an ABRT APDU or data in some user-defined
 * -- abstract syntax.
 * </pre>
 *
 * .......
 *
 * @author amit bhayani
 * @author baranowb
 */
public interface TCUserAbortRequest extends DialogRequest {

    void setReturnMessageOnError(boolean val);

    boolean getReturnMessageOnError();

    /**
     * Sets origin address. This parameter is used only in first TCUserAbort, sent as response to TCBegin. This parameter, if
     * set, changes local peer address(remote end will send request to value set by this method).
     *
     * @return
     */
    SccpAddress getOriginatingAddress();

    void setOriginatingAddress(SccpAddress sccpCallingPartyAddress);

    ApplicationContextName getApplicationContextName();

    void setApplicationContextName(ApplicationContextName applicationContextName);

    UserInformation getUserInformation();

    void setUserInformation(UserInformation userInformation);

    /**
     * Setting of {@link DialogServiceUserType} will create the AARE else ABRT is formed
     *
     * @param dialogServiceUserType
     */
    void setDialogServiceUserType(DialogServiceUserType dialogServiceUserType);

    DialogServiceUserType getDialogServiceUserType();

}
