
package org.restcomm.protocols.ss7.tcapAnsi.api.asn.comp;

import org.restcomm.protocols.ss7.tcapAnsi.api.asn.DialogPortion;
import org.restcomm.protocols.ss7.tcapAnsi.api.asn.Encodable;
import org.restcomm.protocols.ss7.tcapAnsi.api.asn.UserInformationElement;

/**
 *
 * @author baranowb
 * @author sergey vetyutnev

Abort ::= SEQUENCE {
    identifier          TransactionID,
    dialogPortion       DialoguePortion OPTIONAL,
    causeInformation    CHOICE {
        abortCause          P-Abort-cause,
        userInformation     UserAbortInformation    OPTIONAL
    }
}
--When the Abort package is generated by the Transaction sublayer,
--the P-Abort-cause must be present

 *
 */
public interface TCAbortMessage extends Encodable {

    int _TAG_ABORT = 22;
    int _TAG_P_ABORT_CAUSE = 23;
    int _TAG_USER_ABORT_INFORMATION = 24;

    byte[] getDestinationTransactionId();

    void setDestinationTransactionId(byte[] t);

    DialogPortion getDialogPortion();

    void setDialogPortion(DialogPortion dp);

    PAbortCause getPAbortCause();

    void setPAbortCause(PAbortCause t);

    UserInformationElement getUserAbortInformation();

    void setUserAbortInformation(UserInformationElement uai);

}
