package org.restcomm.protocols.ss7.isup.message.parameter;

import org.restcomm.protocols.ss7.isup.ParameterException;

/**
 * @author baranowb
 * @author sergey vetyutnev
 *
 */
public enum ReturnResultProblemType {

    /**
     * No operation with the specified invoke ID is in progress. This code is generated by the TCAP layer.
     */
    UnrecognizedInvokeID(0),

    /**
     * The invoked operation does not report success. This code is generated by the TCAP layer.
     */
    ReturnResultUnexpected(1),

    /**
     * Signifies that the type of parameter in the return result component is not that agreed by the two TC-Users. This code is
     * generated by the TC-User (not by TCAP layer).
     */
    MistypedParameter(2);

    ReturnResultProblemType(long l) {
        this.type = l;
    }

    private long type;

    /**
     * @return the type
     */
    public long getType() {
        return type;
    }

    public static ReturnResultProblemType getFromInt(long t) throws ParameterException {
        if (t == 0) {
            return UnrecognizedInvokeID;
        } else if (t == 1) {
            return ReturnResultUnexpected;
        } else if (t == 2) {
            return MistypedParameter;
        }
        throw new ParameterException( "Wrong value of type: " + t);
    }
}
